[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
fileWatcherType = "auto"
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#374151"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f4f6"
textColor = "#111827"
font = "sans serif"
